#!/bin/bash
 
# Declare a string array with type
declare -a StringArray=( "acceller.com" "acceller.com.acceller.com" "al1.acceller.com" "bms1.acceller.com" "builds.acceller.com" "callcenter1.acceller.com" "callcenter3.acceller.com" "cms.acceller.com" "uat.commnet.acceller.com" "comnet.acceller.com" "cts-staging.acceller.com" "cts-uat.acceller.com" "cts1-dev.acceller.com" "cts1-qaf.acceller.com" "cts1-qis.acceller.com" "cts2-qis.acceller.com" "cts5-qis.acceller.com" "ctslb-qis.acceller.com" "dev.acceller.com" "devop2.acceller.com" "diagnosticapp.acceller.com" "directv.acceller.com" "dnsadmin.acceller.com" "docs.acceller.com" "dtv.acceller.com" "uat.dtv.acceller.com" "dtvdl.acceller.com" "dtvdr.acceller.com" "dtvtemp.acceller.com" "dtvtest.acceller.com" "eot-staging.acceller.com" "eot-uat.acceller.com" "export.acceller.com" "externalordertracker1.acceller.com" "extranetstaging.acceller.com" "focus.acceller.com" "ftp.acceller.com" "gadgets.acceller.com" "gemini-t.acceller.com" "gemini.acceller.com" "genftp.acceller.com" "git.acceller.com" "hawk1.acceller.com" "hawk2.acceller.com" "hawk3.acceller.com" "hawkeye-web.acceller.com" "hduat.acceller.com" "hpuat.acceller.com" "im.acceller.com" "im20.acceller.com" "intranet.acceller.com" "it.acceller.com" "kace.acceller.com" "login.acceller.com" "margae.acceller.com" "mobile.acceller.com" "mon.acceller.com" "mon2.acceller.com" "ns1.acceller.com" "ns2.acceller.com" "nstat.acceller.com" "ops.acceller.com" "ots-staging.acceller.com" "ots-uat.acceller.com" "owl.acceller.com" "portal.acceller.com" "provider.acceller.com" "providerflash.acceller.com" "prtg-den.acceller.com" "prtg-hq.acceller.com" "prtg-prod.acceller.com" "qa-fwsprod.acceller.com" "qaf-sftp.acceller.com" "repserver.acceller.com" "reseller.acceller.com" "robin1.acceller.com" "robin3.acceller.com" "search.acceller.com" "sftp.acceller.com" "sftp1.acceller.com" "sftpsrv.acceller.com" "summit.acceller.com" "www.summit.acceller.com" "testaddress.acceller.com" "testaws.acceller.com" "testawsadp.acceller.com" "testcomnet.acceller.com" "testservices.acceller.com" "testservicesinternal.acceller.com" "tms.acceller.com" "tripwire.acceller.com" "uat-vlc.acceller.com" "uat.acceller.com" "uataws.acceller.com" "uatcomnet.acceller.com" "uaws2.acceller.com" "uextranet.acceller.com" "utilities.acceller.com" "www.utilities.acceller.com" "verizontest.acceller.com" "vpn.acceller.com" "vpn1.acceller.com" "vpn2.acceller.com" "vss.acceller.com" "wiki-old.acceller.com" "wp.acceller.com" "wug.acceller.com" "www1.acceller.com" "www3.acceller.com" )
 
# Read the array values with space
for val in "${StringArray[@]}"; do
  nslookup -type=[A] $val andy.ns.cloudflare.com | grep "** server can't find" | awk '{print $5}' > errorA.txt 
done
